version: '3'
services:
  ecomm-backend-app:
    container_name: ecomm_backend_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  postgres:
    container_name: postgres_database
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
